### ISSUE TITLE
[관리자] Image Upscaler

### ISSUE THREAD

**Issue by 2hanbyeol1** [Liberty52/admin-page#77]
### API
https://github.com/Liberty52/product/issues/256
```yaml
method: POST
url: /images/upscaling

request-body:
  url: string # image url to upscale
  scale: number # 2 for X2, 3 for X3, 4 for X4
```
